# Generated by Django 3.0.3 on 2020-05-11 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('S', 'Seasonal'), ('BA', 'Before/After'), ('P', 'One Time Period')], default='P', max_length=100)),
                ('public', models.BooleanField()),
                ('town', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Datafile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adultEquiv', models.FloatField()),
                ('numStoves', models.IntegerField()),
                ('numPmMeasurementLocations', models.IntegerField()),
                ('numFUEL', models.IntegerField()),
                ('numLogs', models.IntegerField()),
                ('typeStoveData', models.CharField(max_length=250)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuelsite.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuelType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('householdNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stoveType', models.CharField(max_length=100)),
                ('organization', models.ManyToManyField(to='fuelsite.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='StoveMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookingEventsDay', models.IntegerField()),
                ('cookingTime', models.FloatField()),
                ('numDaysLastUse', models.IntegerField()),
                ('totalFuel', models.FloatField()),
                ('AvgDailyFuel', models.FloatField()),
                ('fuelCalibrationValue', models.FloatField()),
                ('fuelTareOffset', models.FloatField()),
                ('datafile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuelsite.Datafile')),
                ('fuel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuelsite.Fuel')),
                ('stove', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuelsite.Stove')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('admin', models.BooleanField(default='false')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuelsite.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='UsageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField()),
                ('usage', models.FloatField()),
                ('stove', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuelsite.StoveMetadata')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField()),
                ('usage', models.FloatField()),
                ('stove', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuelsite.StoveMetadata')),
            ],
        ),
        migrations.CreateModel(
            name='StoveAdditionalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('stove', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuelsite.StoveMetadata')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdAdditionalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('household', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuelsite.Household')),
            ],
        ),
        migrations.AddField(
            model_name='household',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuelsite.Organization'),
        ),
        migrations.CreateModel(
            name='FuelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField()),
                ('usage', models.FloatField()),
                ('stove', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuelsite.StoveMetadata')),
            ],
        ),
        migrations.AddField(
            model_name='fuel',
            name='organization',
            field=models.ManyToManyField(to='fuelsite.Organization'),
        ),
        migrations.CreateModel(
            name='DatafileAdditionalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('datafile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuelsite.Datafile')),
            ],
        ),
        migrations.AddField(
            model_name='datafile',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuelsite.Household'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuelsite.Organization'),
        ),
    ]
